management.endpoints.web.exposure.include: "*"

spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://35.241.229.25:3306/demo_kubernetes?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: demo_kubernetes
    password: demo_kubernetes
    driver-class-name: com.mysql.cj.jdbc.Driver
