management.endpoints.web.exposure.include: "*"

hazelcast.max.no.heartbeat.seconds: 6

admin-application.url: http://35.210.184.122:8080/admin/ui/

news-application.url: http://35.210.184.122:8080/news/ui/
